# Generated by Django 4.2.7 on 2023-12-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='cluster',
            field=models.IntegerField(null=True),
        ),
    ]
