# Generated by Django 4.2.7 on 2023-12-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_surveyresponse_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='cluster',
        ),
    ]
